Solved the first questions of homework 3
ubercareerprep2021/Uber-Career-Prep-Homework-Luis-Sales pull request #5
Opened 2021-08-26 19:46 UTC by luisfilipels

2021-08-27 18:03 UTC, kunwang555 commented on src/Assignment3/sorting/SortEx1.kt
> +    println(testArray.contentToString())
var expectedValue = intArrayOf(5, 5, 5, 5, 10, 10, 20)
var actualValue = testArray
assure.equals(expectedValue, actualValue)

2021-08-27 18:06 UTC, kunwang555 commented on src/Assignment3/sorting/SortEx1.kt
> +    println(testArray.contentToString())
https://kotlinlang.org/docs/jvm-test-using-junit.html#create-a-test

2021-08-27 18:08 UTC, kunwang555 requested changes
Please add some test cases

2021-08-27 18:10 UTC, kunwang555 commented on src/Assignment3/sorting/SortEx1.kt
> +    fun threePartitionSort(array: IntArray) {
add comments on the method/function to tell what the purpose of the method. or link to the question.

2021-08-31 23:50 UTC, luisfilipels commented
Added test cases and comments to the first question. Moving on to the next questions.

2021-09-01 16:49 UTC, kunwang555 commented
@luisfilipels Please let me know once you finished all the changes, and I will review it again. overall those test cases looks good to me

2021-09-01 19:51 UTC, luisfilipels commented
Added tests and comments to all sorting-related questions. Is it ok to merge?

2021-09-01 23:44 UTC, kunwang555 approved these changes
please merge.

2021-09-01 23:46 UTC, merged